export const sample_foods: {}[] = [
  {
    name: "Pizza Pepperoni",
    cookTime: "10-20",
    price: 10,
    favourite: false,
    origins: ["italy"],
    stars: 4.5,
    imageUrl: "assets/food-1.jpg",
    tags: ["FastFood", "Pizza", "Lunch"],
  },
  {
    name: "Meat ball",
    price: 20,
    cookTime: "20-30",
    favourite: true,
    origins: ["persia", "middle east", "china"],
    stars: 4.7,
    imageUrl: "assets/food-2.jpg",
    tags: ["SlowFood", "Lunch"],
  },
  {
    name: "Hamburger",
    price: 5,
    cookTime: "10-15",
    favourite: false,
    origins: ["germany", "us"],
    stars: 3.5,
    imageUrl: "assets/food-3.jpg",
    tags: ["FastFood", "Hamburger"],
  },
  {
    name: "Fried Potatoes",
    price: 2,
    cookTime: "15-20",
    favourite: true,
    origins: ["belgium", "france"],
    stars: 3.3,
    imageUrl: "assets/food-4.jpg",
    tags: ["FastFood", "Fry"],
  },
  {
    name: "Chicken Soup",
    price: 11,
    cookTime: "40-50",
    favourite: false,
    origins: ["india", "asia"],
    stars: 3.0,
    imageUrl: "assets/food-5.jpg",
    tags: ["SlowFood", "Soup"],
  },
  {
    name: "Vegetables Pizza",
    price: 9,
    cookTime: "40-50",
    favourite: false,
    origins: ["italy"],
    stars: 4.0,
    imageUrl: "assets/food-6.jpg",
    tags: ["FastFood", "Pizza", "Lunch"],
  },
];

export const sample_tags: any[] = [
  { name: "All", count: 6 },
  { name: "FastFood", count: 4 },
  { name: "Pizza", count: 2 },
  { name: "Lunch", count: 3 },
  { name: "SlowFood", count: 2 },
  { name: "Hamburger", count: 1 },
  { name: "Fry", count: 1 },
  { name: "Soup", count: 1 },
];
export const sample_users: any[] = [
  {
    name: "Saad",
    email: "saad.elnady@gmail.com",
    password: "123456789",
    address: "Mansoura",
    isAdmin: true,
  },
  {
    name: "Mostafa",
    email: "mostafa22@gmail.com",
    password: "12541254111",
    address: "Maadi",
    isAdmin: false,
  },
];
